import java.util.*;

//FOR ABSTRACTION
interface Optionals {
    //USER CAPABILITIES
    void Register(int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve);
    void CheckReservation( int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve);
    void EditReservation(int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve);
    
    void RemoveReservation(int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve);
    void forgotPassword(int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve);

    //ADMIN CAPABILITIES
    void SetReservation( int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve );

    void ExportList( int patientLimit1, int patientLimit2, int patientLimit3, int  patientLimit4, int patientLimit5,
    int attempts1, int attempts2, int attempts3, int attempts4, int attempts5, 
    String date1, String date2, String date3, String date4, String date5, 
    String vaccinationSite1, String vaccinationSite2, String vaccinationSite3, String vaccinationSite4, String vaccinationSite5,
    String vaccinator1, String vaccinator2, String vaccinator3, String vaccinator4, String vaccinator5,
    String doctor1, String doctor2, String doctor3, String doctor4, String doctor5,
    String start1, String start2, String start3, String start4, String start5,
    String end1, String end2,  String end3,  String end4,  String end5,
    Scanner input, Implement imp,
    LinkedHashMap<String, String> nameList1, LinkedHashMap<String, String> nameList2, LinkedHashMap<String, String> nameList3, LinkedHashMap<String, String> nameList4, LinkedHashMap<String, String> nameList5, 
    LinkedHashMap<String, Integer> ageList1, LinkedHashMap<String, Integer> ageList2, LinkedHashMap<String, Integer> ageList3,LinkedHashMap<String, Integer> ageList4, LinkedHashMap<String, Integer> ageList5,
    LinkedHashMap<String, String> mobileNum1, LinkedHashMap<String, String> mobileNum2,LinkedHashMap<String, String> mobileNum3,
    LinkedHashMap<String, String> mobileNum4, LinkedHashMap<String, String> mobileNum5,
    LinkedHashMap<String, String> addresses1, LinkedHashMap<String, String> addresses2,LinkedHashMap<String, String> addresses3,LinkedHashMap<String, String> addresses4,LinkedHashMap<String, String> addresses5,
    LinkedHashMap<String, String> IDs1, LinkedHashMap<String, String> IDs2, LinkedHashMap<String, String> IDs3, LinkedHashMap<String, String> IDs4, LinkedHashMap<String, String> IDs5,
    LinkedHashMap<String, String> passList1, LinkedHashMap<String, String> passList2, LinkedHashMap<String, String> passList3, LinkedHashMap<String, String> passList4, LinkedHashMap<String, String> passList5,
    LinkedHashMap<String, String> middleName1, LinkedHashMap<String, String> middleName2, LinkedHashMap<String, String> middleName3, LinkedHashMap<String, String> middleName4, LinkedHashMap<String, String> middleName5,
    LinkedHashMap<String, String> timeList1, LinkedHashMap<String, String> timeList2, LinkedHashMap<String, String> timeList3, LinkedHashMap<String, String> timeList4, LinkedHashMap<String, String> timeList5,
    LinkedHashMap<String, String> dateList1, LinkedHashMap<String, String> dateList2, LinkedHashMap<String, String> dateList3, LinkedHashMap<String, String> dateList4, LinkedHashMap<String, String> dateList5,
    LinkedHashMap<String, String> doseName1, LinkedHashMap<String, String> doseName2, LinkedHashMap<String, String> doseName3, LinkedHashMap<String, String> doseName4, LinkedHashMap<String, String> doseName5,
    int choice, boolean setReserve );
}
 